version: '3'
services:
        bot:
                build: .
                networks:
                        - nginx
                volumes:
                        - ./TelegramEDT:/TelegramEDT
                env_file:
                        - webhook_secret.env

networks:
        nginx:
                external: true
