version: '3'
services:
        bot:
                build: .
                networks:
                        - nginx_web
                volumes:
                        - ./TelegramEDT:/TelegramEDT
                env_file:
                        - webhook_secret.env

networks:
        nginx_web:
                external: true
